version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"  # Replace with your GitHub username
    assignees:
      - "your-username"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    labels:
      - "dependencies"
      - "python"
  
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "your-username"  # Replace with your GitHub username
    assignees:
      - "your-username"  # Replace with your GitHub username
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"